version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/picnic-webapp
    overwrite: true
file_exists_behavior: OVERWRITE    
permissions:
  - object: /var/www/html/picnic-webapp
    pattern: "**"
    owner: ubuntu
    group: www-data
    mode: 775