const env = {
  REACT_APP_API_URL: process.env.REACT_APP_API_URL,
  REACT_APP_LANGUAGE: process.env.REACT_APP_LANGUAGE,
  REACT_APP_MEDIA_URL: process.env.REACT_APP_MEDIA_URL,
  REACT_APP_PER_PAGE: process.env.REACT_APP_PER_PAGE,
  REACT_APP_FIRST_PAGE: process.env.REACT_APP_FIRST_PAGE,
  REACT_APP_GOOGLE_API_KEY:process.env.REACT_APP_GOOGLE_API_KEY,
  REACT_APP_TIME_FORMAT: process.env.REACT_APP_TIME_FORMAT

  
}
export default env;